// Automatically Generated by Ed - https://MooseEd.com
#pragma warning disable IDE0090
#pragma warning disable IDE0044

using System;
using System.Collections.Generic;
using UnityEngine;

namespace EdTech
{
    public partial class EdWorldData
    {
        public const string Name = "New World";

        public const string Level_1 = "Level 1";
        public const string Level_2 = "Level 2";

        public static EdTileDef sprite___walls_11 = new EdTileDef
        {
            Id = "06cbcf09-96ba-4929-af86-9a3c502299db",
            Ref = "sprite___walls_11",
            Handle = 36u,
            CollisionMode = (EdTileCollisionMode)1,
            Animation = new EdTileAnimation
            {
                Rate = (float)4.0,
                KeyFrames = new EdSpriteKeyFrame[]
                {
                    new ("__walls_11"),
                }
            },
        };

        public static EdTileDef sprite___walls_5 = new EdTileDef
        {
            Id = "0fdb4b13-0675-4e67-a854-75b640192573",
            Ref = "sprite___walls_5",
            Handle = 30u,
            CollisionMode = (EdTileCollisionMode)1,
            Animation = new EdTileAnimation
            {
                Rate = (float)4.0,
                KeyFrames = new EdSpriteKeyFrame[]
                {
                    new ("__walls_5"),
                }
            },
        };

        public static EdTileDef sprite_floor_2 = new EdTileDef
        {
            Id = "16bf9688-6434-4b16-9a45-8ff391313b76",
            Ref = "sprite_floor_2",
            Handle = 9u,
            Animation = new EdTileAnimation
            {
                Rate = (float)4.0,
                KeyFrames = new EdSpriteKeyFrame[]
                {
                    new ("floor_2"),
                }
            },
        };

        public static EdTileDef sprite_floor_0 = new EdTileDef
        {
            Id = "220a8e91-7fff-4a77-889e-2c681314f53d",
            Ref = "sprite_floor_0",
            Handle = 7u,
            Animation = new EdTileAnimation
            {
                Rate = (float)4.0,
                KeyFrames = new EdSpriteKeyFrame[]
                {
                    new ("floor_0"),
                }
            },
        };

        public static EdTileDef sprite___walls_8 = new EdTileDef
        {
            Id = "483b643e-4351-4574-8842-dd3522e5b9cb",
            Ref = "sprite___walls_8",
            Handle = 33u,
            CollisionMode = (EdTileCollisionMode)1,
            Animation = new EdTileAnimation
            {
                Rate = (float)4.0,
                KeyFrames = new EdSpriteKeyFrame[]
                {
                    new ("__walls_8"),
                }
            },
        };

        public static EdTileDef sprite___walls_9 = new EdTileDef
        {
            Id = "6f810180-6fb4-469d-bafc-25b4136760c4",
            Ref = "sprite___walls_9",
            Handle = 34u,
            CollisionMode = (EdTileCollisionMode)1,
            Animation = new EdTileAnimation
            {
                Rate = (float)4.0,
                KeyFrames = new EdSpriteKeyFrame[]
                {
                    new ("__walls_9"),
                }
            },
        };

        public static EdTileDef sprite___walls_6 = new EdTileDef
        {
            Id = "70980c50-f4b8-483e-8543-5fc1db846605",
            Ref = "sprite___walls_6",
            Handle = 31u,
            Anchor = (TileAnchor)4,
            CellAnchor = (TileAnchor)4,
            CollisionMode = (EdTileCollisionMode)1,
            Animation = new EdTileAnimation
            {
                Rate = (float)4.0,
                KeyFrames = new EdSpriteKeyFrame[]
                {
                    new ("__walls_6"),
                }
            },
        };

        public static EdTileDef sprite___walls_13 = new EdTileDef
        {
            Id = "7d5731ad-ccba-4de7-a031-999b34da4eaf",
            Ref = "sprite___walls_13",
            Handle = 38u,
            CollisionMode = (EdTileCollisionMode)1,
            Animation = new EdTileAnimation
            {
                Rate = (float)4.0,
                KeyFrames = new EdSpriteKeyFrame[]
                {
                    new ("__walls_13"),
                }
            },
        };

        public static EdTileDef sprite___walls_12 = new EdTileDef
        {
            Id = "8a4c45bc-98e4-4c15-9d95-0c15e5c482b4",
            Ref = "sprite___walls_12",
            Handle = 37u,
            CollisionMode = (EdTileCollisionMode)1,
            Animation = new EdTileAnimation
            {
                Rate = (float)4.0,
                KeyFrames = new EdSpriteKeyFrame[]
                {
                    new ("__walls_12"),
                }
            },
        };

        public static EdTileDef sprite___walls_10 = new EdTileDef
        {
            Id = "902eb20a-038b-469f-b85e-8b4c1bce9966",
            Ref = "sprite___walls_10",
            Handle = 35u,
            CollisionMode = (EdTileCollisionMode)1,
            Animation = new EdTileAnimation
            {
                Rate = (float)4.0,
                KeyFrames = new EdSpriteKeyFrame[]
                {
                    new ("__walls_10"),
                }
            },
        };

        public static EdTileDef sprite___walls_7 = new EdTileDef
        {
            Id = "a8185553-522c-4f54-97ba-69ee582ab6bf",
            Ref = "sprite___walls_7",
            Handle = 32u,
            CollisionMode = (EdTileCollisionMode)1,
            Animation = new EdTileAnimation
            {
                Rate = (float)4.0,
                KeyFrames = new EdSpriteKeyFrame[]
                {
                    new ("__walls_7"),
                }
            },
        };

        public static EdTileDef sprite___walls_0 = new EdTileDef
        {
            Id = "bb590c9f-efb3-4f4b-8c16-ec3907b4b036",
            Ref = "sprite___walls_0",
            Handle = 27u,
            CollisionMode = (EdTileCollisionMode)1,
            Animation = new EdTileAnimation
            {
                Rate = (float)4.0,
                KeyFrames = new EdSpriteKeyFrame[]
                {
                    new ("__walls_0"),
                }
            },
        };

        public static EdTileDef sprite_floor_1 = new EdTileDef
        {
            Id = "bdd50453-9c7b-42d4-afd8-e905faccf94f",
            Ref = "sprite_floor_1",
            Handle = 8u,
            Animation = new EdTileAnimation
            {
                Rate = (float)4.0,
                KeyFrames = new EdSpriteKeyFrame[]
                {
                    new ("floor_1"),
                }
            },
        };

        public static EdTileDef sprite___walls_14 = new EdTileDef
        {
            Id = "d07f486e-2f40-4166-86e3-4f749c4f34af",
            Ref = "sprite___walls_14",
            Handle = 39u,
            CollisionMode = (EdTileCollisionMode)1,
            Animation = new EdTileAnimation
            {
                Rate = (float)4.0,
                KeyFrames = new EdSpriteKeyFrame[]
                {
                    new ("__walls_14"),
                }
            },
        };

        public static EdTileDef sprite___walls_1 = new EdTileDef
        {
            Id = "ed785c8e-bf4b-4cf9-b1ca-56e92bb2eda6",
            Ref = "sprite___walls_1",
            Handle = 28u,
            CollisionMode = (EdTileCollisionMode)1,
            Animation = new EdTileAnimation
            {
                Rate = (float)4.0,
                KeyFrames = new EdSpriteKeyFrame[]
                {
                    new ("__walls_1"),
                }
            },
        };

        public static EdTileDef sprite___walls_2 = new EdTileDef
        {
            Id = "f7e1fc8a-d4cb-4f61-a159-d2e76aa6a82b",
            Ref = "sprite___walls_2",
            Handle = 29u,
            CollisionMode = (EdTileCollisionMode)1,
            Animation = new EdTileAnimation
            {
                Rate = (float)4.0,
                KeyFrames = new EdSpriteKeyFrame[]
                {
                    new ("__walls_2"),
                }
            },
        };

        public static Dictionary<string, EdTileDef> TileDefs = new Dictionary<string, EdTileDef>
        {
            { "06cbcf09-96ba-4929-af86-9a3c502299db", sprite___walls_11 },
            { "0fdb4b13-0675-4e67-a854-75b640192573", sprite___walls_5 },
            { "16bf9688-6434-4b16-9a45-8ff391313b76", sprite_floor_2 },
            { "220a8e91-7fff-4a77-889e-2c681314f53d", sprite_floor_0 },
            { "483b643e-4351-4574-8842-dd3522e5b9cb", sprite___walls_8 },
            { "6f810180-6fb4-469d-bafc-25b4136760c4", sprite___walls_9 },
            { "70980c50-f4b8-483e-8543-5fc1db846605", sprite___walls_6 },
            { "7d5731ad-ccba-4de7-a031-999b34da4eaf", sprite___walls_13 },
            { "8a4c45bc-98e4-4c15-9d95-0c15e5c482b4", sprite___walls_12 },
            { "902eb20a-038b-469f-b85e-8b4c1bce9966", sprite___walls_10 },
            { "a8185553-522c-4f54-97ba-69ee582ab6bf", sprite___walls_7 },
            { "bb590c9f-efb3-4f4b-8c16-ec3907b4b036", sprite___walls_0 },
            { "bdd50453-9c7b-42d4-afd8-e905faccf94f", sprite_floor_1 },
            { "d07f486e-2f40-4166-86e3-4f749c4f34af", sprite___walls_14 },
            { "ed785c8e-bf4b-4cf9-b1ca-56e92bb2eda6", sprite___walls_1 },
            { "f7e1fc8a-d4cb-4f61-a159-d2e76aa6a82b", sprite___walls_2 },
            { "sprite___walls_11", sprite___walls_11 },
            { "sprite___walls_5", sprite___walls_5 },
            { "sprite_floor_2", sprite_floor_2 },
            { "sprite_floor_0", sprite_floor_0 },
            { "sprite___walls_8", sprite___walls_8 },
            { "sprite___walls_9", sprite___walls_9 },
            { "sprite___walls_6", sprite___walls_6 },
            { "sprite___walls_13", sprite___walls_13 },
            { "sprite___walls_12", sprite___walls_12 },
            { "sprite___walls_10", sprite___walls_10 },
            { "sprite___walls_7", sprite___walls_7 },
            { "sprite___walls_0", sprite___walls_0 },
            { "sprite_floor_1", sprite_floor_1 },
            { "sprite___walls_14", sprite___walls_14 },
            { "sprite___walls_1", sprite___walls_1 },
            { "sprite___walls_2", sprite___walls_2 },
        };

        public static Dictionary<uint, EdTileDef> TileDefHandles = new Dictionary<uint, EdTileDef>
        {
            { 36u, sprite___walls_11 },
            { 30u, sprite___walls_5 },
            { 9u, sprite_floor_2 },
            { 7u, sprite_floor_0 },
            { 33u, sprite___walls_8 },
            { 34u, sprite___walls_9 },
            { 31u, sprite___walls_6 },
            { 38u, sprite___walls_13 },
            { 37u, sprite___walls_12 },
            { 35u, sprite___walls_10 },
            { 32u, sprite___walls_7 },
            { 27u, sprite___walls_0 },
            { 8u, sprite_floor_1 },
            { 39u, sprite___walls_14 },
            { 28u, sprite___walls_1 },
            { 29u, sprite___walls_2 },
        };

        public static EdTileDef GetTileDef(uint handle)
        {
            if (TileDefHandles.TryGetValue(handle, out var tileDef))
                return tileDef;
            return null;
        }

        public static EdTileDef GetTileDef(string lookup)
        {
            if (TileDefs.TryGetValue(lookup, out var tileDef))
                return tileDef;
            return null;
        }

        public static string[] LevelGuids = new string[]
        {
            "fe441a9715e540ed8e3f607ebbd00c9a",
            "d05eeb70d5244b2c99e1b0d0b1351fed",
        };

        public static Dictionary<long, EdDataContainer> DataContainers = new Dictionary<long, EdDataContainer>
        {
        };
    }
}

#pragma warning restore IDE0044
#pragma warning restore IDE0090

